export const routePaths = {
  home: "/",
  about: "/about",
  campaings: "/campaings",
  services: "/services",
  login: "/login",
  signup: "/signup",
  usernamepassword: "/usernamepassword",
  emailverify: "/emailverify",
  step1: "/create-campaignStep1",
  step2: "/create-campaignStep2",
  step3: "/create-campaignStep3",
  step4: "/create-campaignStep4",
  step5:"/create-campaignStep5",
  done:"/done",
  donate:"/donate",
};
